add_newline = true 

prompt_order = [
    "directory",
    "git_branch",
    "git_commit",
    "git_status",
    "package",
    "line_break",
    "character"
]

[character]
symbol = "Î» â€º"
vicmd_symbol = "Î» Â·"
style_success = "white"
style_failure = "red"

[cmd_duration]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false
style = "purple"

[git_branch]
symbol = "ï˜ "
style = "blue"

[git_status]
style = "green"

[golang]
symbol = "î˜§ "
disabled = true

[elixir]
symbol = "ğŸ”®"
disabled = true

[java]
symbol = "î‰– "
disabled = true

[package]
symbol = "ï£– "
disabled = true

[python]
symbol = "î˜† "
disabled = true

[rust]
symbol = "ï€“ "
disabled = true

scan_timeout = 10
